# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngRPC.proto\x12\x07student\"\x1c\n\x0eGetNameRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x0fGetNameResponse\x12\x11\n\tfull_name\x18\x01 \x01(\t\"D\n\x16GetAverageScoreRequest\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x0c\n\x02id\x18\x02 \x01(\x05H\x00\x42\x0c\n\nidentifier\"0\n\x17GetAverageScoreResponse\x12\x15\n\raverage_score\x18\x01 \x01(\x01\"\x1d\n\x0fGetGroupRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\x10GetGroupResponse\x12\r\n\x05group\x18\x01 \x01(\t2\xeb\x01\n\x0eStudentService\x12>\n\x07GetName\x12\x17.student.GetNameRequest\x1a\x18.student.GetNameResponse\"\x00\x12V\n\x0fGetAverageScore\x12\x1f.student.GetAverageScoreRequest\x1a .student.GetAverageScoreResponse\"\x00\x12\x41\n\x08GetGroup\x12\x18.student.GetGroupRequest\x1a\x19.student.GetGroupResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETNAMEREQUEST']._serialized_start=23
  _globals['_GETNAMEREQUEST']._serialized_end=51
  _globals['_GETNAMERESPONSE']._serialized_start=53
  _globals['_GETNAMERESPONSE']._serialized_end=89
  _globals['_GETAVERAGESCOREREQUEST']._serialized_start=91
  _globals['_GETAVERAGESCOREREQUEST']._serialized_end=159
  _globals['_GETAVERAGESCORERESPONSE']._serialized_start=161
  _globals['_GETAVERAGESCORERESPONSE']._serialized_end=209
  _globals['_GETGROUPREQUEST']._serialized_start=211
  _globals['_GETGROUPREQUEST']._serialized_end=240
  _globals['_GETGROUPRESPONSE']._serialized_start=242
  _globals['_GETGROUPRESPONSE']._serialized_end=275
  _globals['_STUDENTSERVICE']._serialized_start=278
  _globals['_STUDENTSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
